FROM 358559522285.dkr.ecr.us-west-2.amazonaws.com/base-php84:8.4-amzn2023-r2

# Set up custom INI, disable AppSec, install AST and Composer
RUN mkdir -p /tmp/custom-ini \
    && echo 'datadog.appsec.enabled=Off' > /tmp/custom-ini/disable-appsec.ini \
    && pecl install ast \
    && echo "extension=ast.so" > /tmp/custom-ini/enable-ast.ini \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

ENV PHP_INI_SCAN_DIR="/etc/php.d:/tmp/custom-ini"

WORKDIR /app
COPY . .

# Clean install without lock/vendor
RUN rm -f composer.lock && rm -rf vendor/ && composer install

# Disable default Apache entrypoint
ENTRYPOINT []
