FROM 358559522285.dkr.ecr.us-west-2.amazonaws.com/base-php74:7.4-amzn2

# Install AST extension and Composer, set PHP ini path
RUN mkdir -p /tmp/custom-ini \
    && pecl install ast \
    && echo "extension=ast.so" > /tmp/custom-ini/enable-ast.ini \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

ENV PHP_INI_SCAN_DIR="/etc/php.d:/tmp/custom-ini"

WORKDIR /app
COPY . .

# Clean install without lock/vendor
RUN rm -f composer.lock && rm -rf vendor/ && composer install

# Disable default Apache entrypoint
ENTRYPOINT []
